language: generic 
sudo: required
services:
  - docker
before_install:
    - docker build -t amitdocker/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true amitdocker/docker-react npm run test
