language: generic 
sudo: required
services:
  - docker
before_install:
    - docker build -t amitdocker/docker-react -f Dockerfile.dev .

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-446738417440"
  bucket_path: "docker-react"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

